fkie-cad/cwe_checker

- Dockerfile
this should solve the docker container creation issues
> system upgrade

- Dockerfile
- README.md
Before merge please check if it still works as expected.
> docker optimized and markdown issues fixed

- CHANGES.md
- README.md
- cwe_checker_to_ida/CweCheckerParser.py
- cwe_checker_to_ida/CweCheckerParser_test.py
- cwe_checker_to_ida/Generator.py
- cwe_checker_to_ida/cwe_checker_to_ida.py
- plugins/cwe_checker/cwe_checker.ml
- src/checkers/cwe_190.ml
- src/utils/log_utils.ml
- src/utils/log_utils.mli
> Fix cwe_checker_to_ida, which was broken due to refactoring of logging

- src/checkers/cwe_215.ml
- src/utils/cconv.ml
Had to alter the parsing function parse_dyn_sym_line and parse_dyn_syms.
> switched from readelf to objdump in cwe_215.ml and cconv.ml.

- caller/cwe_checker.ml
- index.mld
- src/main.ml
- src/main.mli
Add "--version" to command line options.
> Version number

- cwe_checker_rs/src/analysis/pointer_inference/context/tests.rs
- cwe_checker_rs/src/analysis/pointer_inference/object_list.rs
- cwe_checker_rs/src/analysis/pointer_inference/state/mod.rs
Simplify the implementation of object list, as it contained some unnecessary complexity.
> simplify object list

- cwe_checker_rs/src/checkers.rs
- cwe_checker_rs/src/checkers/cwe_190.rs
- cwe_checker_rs/src/checkers/cwe_332.rs
- cwe_checker_rs/src/checkers/cwe_426.rs
- cwe_checker_rs/src/checkers/cwe_467.rs
- cwe_checker_rs/src/checkers/cwe_560.rs
- cwe_checker_rs/src/lib.rs
- cwe_checker_rs/src/utils/symbol_utils.rs
- test/src/lib.rs
This PR reimplements the checks for CWE 190, CWE 332 and CWE 426 in Rust.
> Implement more checks in Rust.

- .github/workflows/codestyle_checks.yml
- caller/src/main.rs
- cwe_checker_rs/src/analysis/pointer_inference/context/mod.rs
- cwe_checker_rs/src/analysis/pointer_inference/object.rs
- cwe_checker_rs/src/bil/mod.rs
- cwe_checker_rs/src/ffi/serde.rs
- cwe_checker_rs/src/intermediate_representation/term.rs
- cwe_checker_rs/src/pcode/expressions.rs
- cwe_checker_rs/src/pcode/term.rs
This PR adds Github actions for Rustfmt and clippy.
> add GitHub actions for Rustfmt and clippy

- cwe_checker_rs/src/abstract_domain/bitvector.rs
- cwe_checker_rs/src/abstract_domain/data.rs
- cwe_checker_rs/src/abstract_domain/mem_region.rs
- cwe_checker_rs/src/abstract_domain/mod.rs
- cwe_checker_rs/src/abstract_domain/pointer.rs
- cwe_checker_rs/src/analysis/pointer_inference/context/tests.rs
- cwe_checker_rs/src/analysis/pointer_inference/object_list.rs
- cwe_checker_rs/src/analysis/pointer_inference/state/access_handling.rs
- cwe_checker_rs/src/analysis/pointer_inference/state/mod.rs
- cwe_checker_rs/src/analysis/pointer_inference/state/tests.rs
- cwe_checker_rs/src/checkers/cwe_476/context.rs
- cwe_checker_rs/src/checkers/cwe_476/state.rs
- cwe_checker_rs/src/checkers/cwe_476/taint.rs
- cwe_checker_rs/src/checkers/cwe_782.rs
- cwe_checker_rs/src/intermediate_representation/expression.rs
- cwe_checker_rs/src/intermediate_representation/expression/builder.rs
- cwe_checker_rs/src/utils/binary.rs
- cwe_checker_rs/src/utils/log.rs
Several small code improvements that were on my personal TODO list.
> Small improvements

- caller/src/main.rs
Better error messages if the execution of Ghidra fails. Also prevents printing a stack backtrace in this case because it is irrelevant.
> better error messages on failed Ghidra execution

- cwe_checker_rs/src/pcode/expressions.rs
Fixes parsing of values larger than 64 bits.
> Parse bitvectors larger than 64 bits

- cwe_checker_rs/src/analysis/graph.rs
- cwe_checker_rs/src/analysis/pointer_inference/context/mod.rs
- cwe_checker_rs/src/analysis/pointer_inference/context/trait_impls.rs
- cwe_checker_rs/src/ffi/mod.rs
- cwe_checker_rs/src/ffi/serde.rs
- cwe_checker_rs/src/intermediate_representation/term.rs
- cwe_checker_rs/src/pcode/expressions.rs
Fixes parsing of the FLOAT_CEIL and FLOAT_FLOOR P-Code instructions and thus fixes #141.
I did a pass over all P-Code instructions and these two were the last ones for which we parsed the wrong P-Code mnemonic.
> Pcode parsing

- src/cwe_checker_lib/src/abstract_domain/interval.rs
- src/cwe_checker_lib/src/abstract_domain/interval/simple_interval.rs
- src/cwe_checker_lib/src/abstract_domain/interval/tests.rs
- src/cwe_checker_lib/src/analysis/backward_interprocedural_fixpoint/mod.rs
- src/cwe_checker_lib/src/analysis/forward_interprocedural_fixpoint.rs
- src/cwe_checker_lib/src/checkers/cwe_78.rs
Reworks the implementation of the `Subpiece` and `Piece` operations for the `IntervalDomain` domain to be more exact.
> better Subpiece handling

- src/cwe_checker_lib/src/abstract_domain/interval.rs
- src/cwe_checker_lib/src/abstract_domain/interval/simple_interval.rs
- src/cwe_checker_lib/src/abstract_domain/interval/tests.rs
- src/cwe_checker_lib/src/abstract_domain/pointer.rs
- src/cwe_checker_lib/src/analysis/backward_interprocedural_fixpoint/mod.rs
- src/cwe_checker_lib/src/analysis/forward_interprocedural_fixpoint.rs
- src/cwe_checker_lib/src/analysis/pointer_inference/object_list.rs
- src/cwe_checker_lib/src/analysis/pointer_inference/state/mod.rs
- src/cwe_checker_lib/src/analysis/pointer_inference/state/tests.rs
- src/cwe_checker_lib/src/checkers/cwe_78.rs
- test/src/lib.rs
Handle simple cases of pointer comparisons when specializing via conditional jumps during Pointer Inference algorithm.
> Pointer comparison

- CHANGES.md
- Makefile
- README.md
- src/caller/Cargo.toml
- src/cwe_checker_lib/Cargo.toml
Update the README.md and CHANGES.md in preparation of the upcoming v0.5 stable release. Also update the version numbers in the Cargo.toml files.
Note that PR #189 needs to be merged before this PR.
> Prepare for v0.5 stable release

- src/caller/Cargo.toml
- src/cwe_checker_lib/Cargo.toml
To kick off development of the next version in the master branch.
> update version number to 0.6-dev

- Dockerfile
- README.md
- src/caller/Cargo.toml
- src/cwe_checker_lib/Cargo.toml
- src/cwe_checker_lib/src/checkers/cwe_476/state.rs
- test/Cargo.toml
Switch to the new Rust 2021 edition.
> switch to Rust 2021 edition

- Dockerfile
Everyone should update their Ghidra versions right now!
> Update Ghidra version in the Docker image to 10.1

- src/cwe_checker_lib/src/analysis/function_signature/context/tests.rs
- src/cwe_checker_lib/src/analysis/function_signature/state/tests.rs
- src/cwe_checker_lib/src/analysis/pointer_inference/state/tests.rs
- src/cwe_checker_lib/src/checkers/cwe_134.rs
- src/cwe_checker_lib/src/intermediate_representation/sub.rs
- src/cwe_checker_lib/src/utils/arguments/tests.rs
- src/cwe_checker_lib/src/utils/binary.rs
Tests for calling conventions edited for meeting System V ABI/ARM32 ABI and Ghidras output.
> Test reorganization

- CHANGES.md
- Cargo.lock
- README.md
- src/caller/Cargo.toml
- src/cwe_checker_lib/Cargo.toml
- src/cwe_checker_lib/src/checkers/cwe_332.rs
- src/cwe_checker_lib/src/lib.rs
- test/Cargo.toml
Update Readme, Changelog and version numbers in preparation of the release of the next stable version v0.6.
> Prepare release of stable version v0.6

- src/caller/src/main.rs
- src/cwe_checker_lib/src/abstract_domain/data.rs
- src/cwe_checker_lib/src/abstract_domain/interval.rs
- src/cwe_checker_lib/src/checkers/cwe_190.rs
Added Pointer Inference results for detecting CWE190.
> added Pointer Inference results as basis for overflow detection.

- src/cwe_checker_lib/src/checkers/cwe_119/context/mod.rs
Fix a bug in the CWE119 check that lead to some integer overflows not being detected, which in turn lead to assigning negative size values to memory objects allocated by functions like `malloc` in some rare cases.
> CWE119-check: Fix errorneous integer overflow detection

- src/cwe_checker_lib/src/analysis/pointer_inference/mod.rs
- src/cwe_checker_lib/src/checkers/cwe_467.rs
- src/cwe_checker_lib/src/checkers/cwe_560.rs
- src/cwe_checker_lib/src/intermediate_representation/blk.rs
- src/cwe_checker_lib/src/intermediate_representation/def.rs
- src/cwe_checker_lib/src/intermediate_representation/expression.rs
- src/cwe_checker_lib/src/intermediate_representation/expression/tests.rs
- src/cwe_checker_lib/src/intermediate_representation/jmp.rs
Implemented the Display Trait for Expression by using somewhat intuitive symbols.
> added Display trait for Expression and Operants

- src/cwe_checker_lib/src/analysis/function_signature/access_pattern.rs
- src/cwe_checker_lib/src/analysis/function_signature/context.rs
- src/cwe_checker_lib/src/analysis/function_signature/context/tests.rs
- src/cwe_checker_lib/src/analysis/function_signature/mod.rs
- src/cwe_checker_lib/src/analysis/function_signature/state.rs
- src/cwe_checker_lib/src/analysis/function_signature/state/call_handling.rs
- src/cwe_checker_lib/src/analysis/function_signature/state/tests.rs
- src/cwe_checker_lib/src/analysis/function_signature/stubs.rs
- src/cwe_checker_lib/src/checkers/cwe_134.rs
- src/cwe_checker_lib/src/intermediate_representation/sub.rs
- src/cwe_checker_lib/src/utils/arguments.rs
- src/cwe_checker_lib/src/utils/arguments/tests.rs
Add stubs for common LibC-functions to the function signature analysis.
> Add function stubs to function signature analysis

- src/cwe_checker_lib/src/analysis/dead_variable_elimination/mod.rs
- src/cwe_checker_lib/src/analysis/function_signature/context/tests.rs
- src/cwe_checker_lib/src/intermediate_representation/expression.rs
- src/cwe_checker_lib/src/intermediate_representation/expression/tests.rs
- src/cwe_checker_lib/src/intermediate_representation/macros.rs
- src/cwe_checker_lib/src/intermediate_representation/mod.rs
- src/cwe_checker_lib/src/pcode/subregister_substitution/tests.rs
- src/cwe_checker_lib/src/pcode/term/tests.rs
First changes for introducing macros to the test code base. All further changes are done as PR to macros_and_test_changes for small sized partial reviews.
> Test refactoring step 1

- src/cwe_checker_lib/src/ghidra_pcode/block/mod.rs
- src/cwe_checker_lib/src/ghidra_pcode/block/tests.rs
- src/cwe_checker_lib/src/ghidra_pcode/function/mod.rs
- src/cwe_checker_lib/src/ghidra_pcode/instruction/mod.rs
- src/cwe_checker_lib/src/ghidra_pcode/mod.rs
- src/cwe_checker_lib/src/ghidra_pcode/pcode_op_simple/jumps/mod.rs
- src/cwe_checker_lib/src/ghidra_pcode/pcode_op_simple/jumps/tests.rs
- src/cwe_checker_lib/src/ghidra_pcode/pcode_op_simple/mod.rs
- src/cwe_checker_lib/src/ghidra_pcode/pcode_op_simple/tests.rs
- src/cwe_checker_lib/src/ghidra_pcode/varnode/mod.rs
- src/cwe_checker_lib/src/intermediate_representation/term.rs
- src/cwe_checker_lib/src/utils/ghidra.rs
- src/ghidra/p_code_extractor/InstructionSimple.java
implementation and refactoring of jump parsing
> Pcode parser jumps

- CHANGES.md
- Cargo.lock
- src/caller/Cargo.toml
- src/cwe_checker_lib/Cargo.toml
- test/Cargo.toml
Change the version numbers on the master branch, so to officially start development of the next release.
> officially kickstart v0.9 development
