fkie-cad/cwe_checker

CHANGES.md, README.md, recipes/static_analysis/descr, recipes/static_analysis/recipe.scm
A simple recipe for a standard run using the internal rooter of bap.
=> Simple recipe for standard run

CHANGES.md, src/analysis/type_inference.ml, src/analysis/type_inference.mli, src/utils/cconv.ml, test/unit/Makefile, test/unit/analysis/type_inference_test.ml, test/unit/cwe_checker_unit_tests.ml, test/unit/utils/cconv_test.ml, test/unit/utils/cconv_test.mli
adds pointer target tracking to type inference. Practical usefulness is still limited, since the analysis is not interprocedural yet.
=> Type inference

CHANGES.md, README.md, plugins/cwe_checker/cwe_checker.ml, src/checkers/cwe_190.ml, src/utils/log_utils.ml, src/utils/log_utils.mli
- also fixes stuff from review
- returns module versions as valid json document
=> added flag --no-logging to surpress logging to STDOUT

cwe_checker_to_ida/cwe_checker_to_ida.py, dune, index.mld
The *Readme.md* file is not yet adjusted. But I would like to merge this PR first, then publish on Github Pages and then adjust the *Readme.md* file.
=> Add more documentation to odoc-generated docs.

src/analysis/type_inference.ml
I don't know if this function is important to the overall codebase --
I see it used only once in add_mem_address_registers -- but the
previous implementation was a clear code smell; I was browsing the
code during https://2019.pass-the-salt.org/talks/74.html and I thought
that I could go fix it.
The main problem with the previous implementation is that it has
quadratic complexity for deeply-nested expressions. Consider for example:
| Bil.Ite(exp1, exp2, exp3) ->
nested_exp_list exp1 @ nested_exp_list exp2 @ nested_exp_list exp3
the complexity cost of the list concatenations in this sample is
proportional to the size of the result list. If you consider a deep
nesting of 'ite' constructs, you get a quadratic complexity.
The new implementation uses an accumulator; each element in the output …
=> analysis/type_inference: improve the complexity of nested_exp_list

CHANGES.md, README.md, ghidra_plugin/cwe_checker_ghidra_plugin.py, index.mld, src/checkers/cwe_190.ml
This PR adds a plugin for annotating the results of the *cwe_checker* in Ghidra. Its usage is documented in the `ghidra_plugin/cwe_checker_ghidra_plugin.py` file. It is also documented in the generated html documentation. The online documentation will be updated when version 0.3 gets published, which hopefully will be very soon.
=> add Ghidra plugin

ghidra_plugin/cwe_checker_ghidra_plugin.py, src/checkers/cwe_248.ml, test/acceptance/test_file_output.py
This PR fixes two minor bugs and adds a workaround for the address computation of Ghidra, which sometimes adds an offset and sometimes not. There seems to be no function in the Ghidra API that can be used to tell the plugin when this happens and when not.
If the workaround does not work for you (i.e. CWEs imported via the Ghidra plugin are bookmarked at the wrong addresses), please open an issue!
=> Ghidra bugfix

.travis_run_tests.sh, src/checkers/cwe_248.ml, src/utils/symbol_utils.ml, src/utils/symbol_utils.mli, test/unit/cwe_checker_unit_tests.ml, test/unit/utils/cconv_test.ml
This PR fixes two bugs:
- unit tests were not running on Travis CI
- the function get_program_entry_points could return the main function twice in some cases.
=> Enabled unittests for Travis CI. Fixed get_program_entry_points.

.travis.yml, README.md
Migrated to travis-ci.org so that Travis build results are again displayed on pull requests.
=> Migration from travis-ci.org to travis-ci.com

cwe_checker_rs/src/analysis/graph.rs, cwe_checker_rs/src/analysis/pointer_inference/context.rs, cwe_checker_rs/src/analysis/pointer_inference/data.rs, cwe_checker_rs/src/analysis/pointer_inference/object.rs, cwe_checker_rs/src/analysis/pointer_inference/object_list.rs, cwe_checker_rs/src/analysis/pointer_inference/state.rs, src/utils/serde_json.ml
This PR re-inserts return statements that were missing in the control flow graph. It also fixes some bugs found in the process.
=> Fix return

cwe_checker_rs/src/bil/mod.rs, cwe_checker_rs/src/ffi/analysis.rs, cwe_checker_rs/src/term/mod.rs
This PR adds a function to replace let-bindings in expressions with equivalent expressions without let-bindings on the Rust side, so that analyses do not have to cope with let-expressions if they do not want to.
=> replace let-bindings

cwe_checker_rs/src/pcode/expressions.rs, cwe_checker_rs/src/pcode/term.rs, ghidra/p_code_extractor/PcodeExtractor.java
Moves the translation of implicit STORE instructions from Java to Rust. This allows handling of some special cases, which could not be handled on the Java side.
=> Fix implicit stores

caller/src/main.rs, cwe_checker_rs/src/intermediate_representation/expression.rs, cwe_checker_rs/src/intermediate_representation/term.rs, cwe_checker_rs/src/pcode/expressions.rs, cwe_checker_rs/src/pcode/term.rs, cwe_checker_rs/src/term/mod.rs, ghidra/p_code_extractor/PcodeExtractor.java, test/src/lib.rs
This PR adds a normalization pass to the `Project` struct that substitutes trivially computable expressions like `a XOR a` with their result.
The PR should only be merged after the **Fix implicit stores** PR is merged.
=> Substitute trivial expressions

cwe_checker_rs/src/checkers.rs, cwe_checker_rs/src/checkers/cwe_467.rs, cwe_checker_rs/src/lib.rs, test/src/lib.rs
This PR reimplements the check for CWE 467 in Rust.
=> implement check for CWE467 in Rust

cwe_checker_rs/src/analysis/fixpoint.rs, cwe_checker_rs/src/analysis/graph.rs, cwe_checker_rs/src/analysis/interprocedural_fixpoint.rs, cwe_checker_rs/src/analysis/pointer_inference/context/mod.rs, cwe_checker_rs/src/analysis/pointer_inference/context/tests.rs, cwe_checker_rs/src/analysis/pointer_inference/context/trait_impls.rs
This PR adds CallStub edges for indirect calls. We also implement a standard behavior in the Pointer Inference analysis for indirect calls where we know nothing about the call target address. This allows continuation of the Pointer Inference analysis in case of unresolved indirect calls (albeit with lower analysis accuracy).
=> Generic indirect call behaviour

src/checkers/cwe_676.ml
Report the exact address of the call and not only of the basic block containing the call for CWE 676 (with BAP backend).
=> more exact address reporting for CWE 676

cwe_checker_rs/src/abstract_domain/mem_region.rs, cwe_checker_rs/src/analysis/pointer_inference/mod.rs, cwe_checker_rs/src/analysis/pointer_inference/object.rs, cwe_checker_rs/src/analysis/pointer_inference/object_list.rs, cwe_checker_rs/src/checkers/cwe_476/context.rs, cwe_checker_rs/src/checkers/cwe_476/state.rs, cwe_checker_rs/src/intermediate_representation/term.rs
This PR adjusts how CWE hits are detected on function calls and function returns to reduce false positives.
For pointers to the stack as parameters, we underapproximate the values that the call may access to reduce false positives.
For pointers to the heap as parameters, we flag if any possible NULL pointer is contained in the target memory object.
=> Cwe476 parameter checks

README.md, cwe_checker_rs/src/abstract_domain/bitvector.rs, cwe_checker_rs/src/intermediate_representation/expression.rs, cwe_checker_rs/src/pcode/expressions.rs, cwe_checker_rs/src/pcode/term.rs
This PR adds support for the POPCOUNT P-Code instruction introduced in Ghidra 9.2.
As a side effect, we are now fully compatible to Ghidra 9.2 and since Ghidra now includes the Gson library, one does not need to manually add it to Ghidra when installing the cwe_checker.
=> Add the POPCOUNT  expression

cwe_checker_rs/src/abstract_domain/bitvector.rs, cwe_checker_rs/src/abstract_domain/data.rs, cwe_checker_rs/src/abstract_domain/mem_region.rs, cwe_checker_rs/src/abstract_domain/mod.rs, cwe_checker_rs/src/abstract_domain/pointer.rs, cwe_checker_rs/src/checkers/cwe_476/taint.rs
This PR moves the `new_top()` function from the `RegisterDomain` trait to the `HasByteSize` trait. This way we can relax the conditions for the values inside a `MemRegion` from implementing `RegisterDomain` to just implementing `HasTop` and `HasByteSize`.
=> move the new_top() function to the HasByteSize trait.

.github/workflows/acceptance-tests.yml, .github/workflows/unit-tests.yml, Makefile, cwe_checker_rs/src/checkers/cwe_243.rs, test/artificial_samples/Dockerfile, test/artificial_samples/Readme.md
This PR adds Github actions for running unit tests and acceptance tests.
The acceptance tests are running way too slow right now, thus they only run on pull requests right now. Part of the reason is that we cannot run them in parallel without triggering random test failures. Execution of Ghidra for very small input files is also way too slow at the moment, but this is a problem for another PR.
Edit: The PR now also contains a bugfix for the CWE 243 check uncovered by the acceptance tests.
=> Cargo test action

caller/src/main.rs, cwe_checker_rs/src/analysis/backward_interprocedural_fixpoint/tests.rs, cwe_checker_rs/src/analysis/graph.rs, cwe_checker_rs/src/analysis/pointer_inference/context/tests.rs, cwe_checker_rs/src/intermediate_representation/term.rs, cwe_checker_rs/src/pcode/term.rs, cwe_checker_rs/src/pcode/term/tests.rs, cwe_checker_rs/src/term/mod.rs, cwe_checker_rs/src/utils/mod.rs, ghidra/p_code_extractor/internal/TermCreator.java, ghidra/p_code_extractor/term/Program.java
This PR adds an `address_base_offset` field to the program struct. This is the difference between addresses as determined by the binary headers and addresses as determined by Ghidra.
This will be used to enable access to the correct addresses in global memory for analyses (in a future PR).
=> Add address_base_offset field to Program struct

caller/src/main.rs, cwe_checker_rs/src/lib.rs, cwe_checker_rs/src/utils/binary.rs, cwe_checker_rs/src/utils/mod.rs
This PR adds a struct representing the runtime memory image of the binary. 
@mellowCS Since we will use this struct to access global (read-only) variables, please double-check whether the interface covers your use-case. If not, I can extend the interface.
=> Add runtime memory image representation

cwe_checker_rs/src/abstract_domain/bitvector.rs, cwe_checker_rs/src/analysis/pointer_inference/context/mod.rs, cwe_checker_rs/src/analysis/pointer_inference/context/tests.rs, cwe_checker_rs/src/analysis/pointer_inference/context/trait_impls.rs, cwe_checker_rs/src/analysis/pointer_inference/state/mod.rs, cwe_checker_rs/src/analysis/pointer_inference/state/tests.rs
This PR fixes a bug, where the stack register was overwritten on return instructions with its value before the corresponding call. This produced incorrect stack pointer values for x86 and x64 architectures.
=> Bugfix Stack Register Computation

Dockerfile
This PR changes the base image for the docker image to one where Ghidra is already installed. This makes the image a little bit smaller and may also save some build time for the docker image.
=> change base image of dockerfile

cwe_checker_rs/src/intermediate_representation/expression.rs, cwe_checker_rs/src/intermediate_representation/expression/tests.rs, test/src/lib.rs
Substitute more examples of trivial expressions with their results. Also enable more acceptance tests.
It turns out that most of our MIPS-based analyses only failed because the analysis did not know that `a or 0` is always `a`. This is now fixed.
=> Trivial expressions

cwe_checker_rs/src/pcode/expressions.rs
Apparently, Ghidra uses ROUND as a mnemonic for the FLOAT_ROUND p-code operation. At least according to the p-code op code it represents the FLOAT_ROUND p-code operation. This PR fixes the deserialization of it and should be a fix for issue #141.
=> Correctly deserialize FLOAT_ROUND p-code operations

caller/src/main.rs, cwe_checker_rs/src/analysis/pointer_inference/context/mod.rs, cwe_checker_rs/src/analysis/pointer_inference/context/tests.rs, cwe_checker_rs/src/analysis/pointer_inference/mod.rs, cwe_checker_rs/src/checkers/cwe_243.rs, cwe_checker_rs/src/checkers/cwe_367.rs, cwe_checker_rs/src/checkers/cwe_476/context.rs, cwe_checker_rs/src/checkers/cwe_78/context/tests.rs, cwe_checker_rs/src/lib.rs
Provide access to the control flow graph independently of the pointer inference analysis.
Several analyses used the control flow graph but not the results of the pointer inference analysis. They can access the graph now without the need to run the pointer inference analysis first.
=> provide control flow graph independently of pointer inference analysis

src/cwe_checker_lib/src/analysis/backward_interprocedural_fixpoint/tests.rs, src/cwe_checker_lib/src/analysis/graph.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/tests.rs, src/cwe_checker_lib/src/checkers/cwe_78/context/tests.rs, src/cwe_checker_lib/src/intermediate_representation/term.rs, src/cwe_checker_lib/src/pcode/term.rs, src/ghidra/p_code_extractor/internal/TermCreator.java, src/ghidra/p_code_extractor/term/Jmp.java
Parse indirect jump targets from the Ghidra backend and add them to the control flow graph. This PR only handles intraprocedural indirect jumps but not indirect calls!
=> parse indirect jump targets from Ghidra

src/cwe_checker_lib/src/checkers/cwe_560.rs, test/artificial_samples/cwe_560.c
Use better bounds for the umask argument check to prevent some common false positives in the CWE 560 check.
=> CWE560: better bounds for sane umask arguments

src/cwe_checker_lib/src/abstract_domain/bitvector.rs, src/cwe_checker_lib/src/abstract_domain/data.rs, src/cwe_checker_lib/src/abstract_domain/interval.rs, src/cwe_checker_lib/src/abstract_domain/mem_region.rs, src/cwe_checker_lib/src/abstract_domain/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object_list.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/access_handling.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/tests.rs, src/cwe_checker_lib/src/checkers/cwe_467.rs, src/cwe_checker_lib/src/checkers/cwe_476/state.rs, src/cwe_checker_lib/src/checkers/cwe_560.rs, src/cwe_checker_lib/src/checkers/cwe_78/context/tests.rs, src/cwe_checker_lib/src/checkers/cwe_78/state/mod.rs, src/cwe_checker_lib/src/checkers/cwe_78/state/tests.rs, src/cwe_checker_lib/src/utils/binary.rs
Use the interval domain for the pointer inference analysis. We do not yet take advantage of the capabilities of the interval domain (this will be done in the next couple PRs). Instead the pointer inference is generalized (to a degree) so that one can plug in different domains for representing absolute values into the analysis.
=> Use IntervalDomain in Pointer Inference analysis

src/cwe_checker_lib/src/abstract_domain/interval/bin_ops.rs, src/cwe_checker_lib/src/abstract_domain/interval/tests.rs, src/cwe_checker_lib/src/pcode/term.rs, src/cwe_checker_lib/src/pcode/term/tests.rs
Two bugfixes:
- Sometimes the wrong entry point for a function was used. This is now detected and automatically corrected when converting P-Code to the internal intermediate representation.
- In `IntervalDomain` the `shift_left` operation threw an exception for shift amounts larger than the target bitsize instead of setting the result to zero.
=> Bugfix function entry points

src/cwe_checker_lib/src/abstract_domain/interval.rs, src/cwe_checker_lib/src/abstract_domain/interval/bin_ops.rs, src/cwe_checker_lib/src/abstract_domain/interval/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/tests.rs
Add a widening delay to the widening strategy to prevent unnecessary widenings. Also fixes some bugs related to the generation of bound hints.
=> Widening delay

src/cwe_checker_lib/src/pcode/expressions.rs, src/cwe_checker_lib/src/pcode/term.rs, src/cwe_checker_lib/src/pcode/term/tests.rs
Implicit load instructions in the target expression of indirect jumps and calls are now correctly converted to explicit load instructions. We already did that for implicit loads in `Def` instructions, but apparently forgot to implement it for jumps.
=> Implicit load in indirect calls

src/cwe_checker_lib/src/pcode/expressions.rs, src/cwe_checker_lib/src/pcode/term.rs, src/cwe_checker_lib/src/pcode/term/tests.rs
Fixes a bug, where the address size of store instructions was in some cases incorrectly truncated to the byte size of the value to be stored.
=> fix address size of implicit stores

src/ghidra/p_code_extractor/PcodeExtractor.java, src/ghidra/p_code_extractor/internal/JumpProcessing.java, src/ghidra/p_code_extractor/internal/TermCreator.java
- Fixed issue #169 by checking whether the Call has a fallThrough address. Now no Return value is given to the Call.
- Fixed bug where call return pairs were not properly handled when branch instructions were added to the pcode instructions.
* Adding the branch instruction caused the running pcode index to increase but not the number of pcode instructions which
needs to be correct for the CallReturn Handler to be triggered.
- Removed dead parameter from jump processing function.
=> - Fixed issue #169

src/cwe_checker_lib/src/intermediate_representation/expression.rs, src/cwe_checker_lib/src/intermediate_representation/expression/tests.rs, src/ghidra/p_code_extractor/internal/HelperFunctions.java
- The position of sub registers in the base register was sometimes incorrect for 32bit architectures.
- A special case for sub register handling was missing.
=> Fix bug in sub register handling

src/cwe_checker_lib/src/analysis/pointer_inference/context/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/tests.rs, src/cwe_checker_lib/src/checkers/cwe_476/state.rs, src/cwe_checker_lib/src/checkers/cwe_78/state/mod.rs, src/cwe_checker_lib/src/intermediate_representation/term.rs, src/cwe_checker_lib/src/pcode/term.rs, src/cwe_checker_lib/src/pcode/term/tests.rs, src/ghidra/p_code_extractor/PcodeExtractor.java, src/ghidra/p_code_extractor/internal/ParseCspecContent.java, src/ghidra/p_code_extractor/internal/RegisterConvention.java
This PR contains the following changes:
- The input parameter for function calls are now parsed from the corresponding Cspec file provided by Ghidra.
- The Calling Convention struct now contains float and integer parameter separately.
=> Better parameter parsing for external Symbols

src/cwe_checker_lib/src/analysis/pointer_inference/context/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/trait_impls.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object_list.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/access_handling.rs
For cases, where the same dangling pointer is accessed several times in a row, suppress all but the first CWE-416 (use-after-free) warning for it. This reduces the number of duplicate CWE-416 warnings. It should also help in deducing the root cause for a warning, since the remaining warnings are those that are nearest to the corresponding root cause.
=> reduce duplicate CWE-416 warnings

src/cwe_checker_lib/src/analysis/pointer_inference/context/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/trait_impls.rs, src/cwe_checker_lib/src/intermediate_representation/expression.rs, src/cwe_checker_lib/src/intermediate_representation/expression/tests.rs, src/cwe_checker_lib/src/intermediate_representation/term.rs, test/artificial_samples/cwe_78.c, test/src/lib.rs
When specializing a state because of a conditional jump, we used to go through all the `Def`s in the basic block before the jump (in reverse order) and tried to propagate the knowledge that the jump condition evaluates to `true` if the jump was taken. This unfortunately lead to the addition of too many widening hints to some variables, which in turn lead to too coarse widenings for these variables.
Now we use the following tactic instead:
- We propagate known expressions through a basic block as a normalization pass when creating the project struct
- We simplify many more cases of trivially computable expressions
- We only use the actual condition expression for specializing on conditional jumps. Thanks to the first two steps this expression is in most cases already simplified to the …
=> Expression propagation

.github/workflows/codestyle_checks.yml
Missing documentation warnings were already handled as errors when manually running code style checks. Now the CI also handles these as errors.
=> deny missing docs in the CI

src/cwe_checker_lib/src/checkers/cwe_78/context/parameter_detection.rs, src/cwe_checker_lib/src/utils/arguments.rs, src/cwe_checker_lib/src/utils/arguments/tests.rs
The parameter parsing from format strings now allows the developer to log specific errors rather than crashing the analysis in case a format string was externally provided or certain parameters could not be parsed properly.
=> Error Handling for Parameter Parsing

src/cwe_checker_lib/src/analysis/pointer_inference/state/tests.rs, src/cwe_checker_lib/src/checkers/cwe_134.rs, src/cwe_checker_lib/src/checkers/cwe_78/context/parameter_detection.rs, src/cwe_checker_lib/src/checkers/cwe_78/context/tests.rs, src/cwe_checker_lib/src/checkers/cwe_78/state/tests.rs, src/cwe_checker_lib/src/intermediate_representation/expression/builder.rs, src/cwe_checker_lib/src/intermediate_representation/term.rs, src/cwe_checker_lib/src/utils/arguments.rs, src/cwe_checker_lib/src/utils/arguments/tests.rs, src/cwe_checker_lib/src/utils/binary.rs
Mock functions of objects now take a bytesize parameter.
Added two new memory blocks to the memory image mock.
=> Mock objects with bytesize

src/cwe_checker_lib/src/utils/log.rs
Fixes an issue raised in #192 where the error message reported to the user does not explain to the user what went wrong.
=> better error message on output file write error

src/cwe_checker_lib/Cargo.toml, src/cwe_checker_lib/src/abstract_domain/bitvector.rs, src/cwe_checker_lib/src/abstract_domain/interval.rs, src/cwe_checker_lib/src/abstract_domain/interval/bin_ops.rs, src/cwe_checker_lib/src/abstract_domain/interval/simple_interval.rs, src/cwe_checker_lib/src/abstract_domain/interval/simple_interval/tests.rs, src/cwe_checker_lib/src/abstract_domain/interval/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object_list.rs, src/cwe_checker_lib/src/intermediate_representation/bitvector.rs, src/cwe_checker_lib/src/pcode/term.rs, src/cwe_checker_lib/src/utils/symbol_utils.rs
Adds tracking of strides to the interval domain.
This improves the exactness of the interval domain and should reduce the number of instances where bounds of loop counter variables are not correctly identified. As a side effect this should also reduce the number of false positive buffer overflow CWE messages, since many of them are caused by incorrect loop counter variables.
=> add strides to the interval domain

src/cwe_checker_lib/src/analysis/graph.rs, src/cwe_checker_lib/src/intermediate_representation/term.rs, src/cwe_checker_lib/src/pcode/term.rs
Previously, basic blocks were allowed to be contained in several subroutines (e.g. tail calls generated such cases sometimes). This sometimes resulted in subtle bugs, which were difficult to debug.
This PR implements a normalization pass that duplicates blocks contained in several subroutines so that each subroutine has its own unique copy of the basic block, so that analyses can again assume that each block is only contained in one subroutine.
=> Ensure that each block is contained in exactly one subroutine

src/caller/src/main.rs, src/cwe_checker_lib/src/analysis/pointer_inference/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/statistics.rs, src/cwe_checker_lib/src/lib.rs
The purpose of the printed statistics is to help in assessing how well the analysis can handle a particular binary.
=> Add cmdline flag for printing analysis statistics

src/cwe_checker_lib/src/abstract_domain/mem_region.rs, src/cwe_checker_lib/src/abstract_domain/mem_region/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object_list.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/tests.rs
Since the new `DataDomain` does not have a maximal element anymore and uses `Top` as an indicator instead, we have to adjust `MemRegion` accordingly. When merging two `MemRegion` instances, an element only contained in one region gets properly merged with `Top` instead of getting automatically deleted.
As a side effect this further deepens the convergence problems for the Pointer Inference analysis as there are more cases where we track too much information now. So until the whole Pointer Inference analysis is refactored (and a new balance between exactness and convergence is established), the development is not tracked in the master branch but in a separate branch.
=> Refactor MemRegion for usage with new DataDomain

src/cwe_checker_lib/src/analysis/pointer_inference/context/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/trait_impls.rs, src/cwe_checker_lib/src/analysis/pointer_inference/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/mod.rs
Until now the pointer inference analysis was prone to lose track of the global pointer value on MIPS binaries. This in turn meant that accesses to global variables could not be tracked. This PR mitigates the issue with the following workarounds:
* On a function call we ensure that the `t9` register is set to the callee address (in accordance with the System V ABI for MIPS). This ensures that the value of `gp` can be correctly computed at the start of a function.
* We also set the `t9` register for entry points.
* After a return from a function call the value of `gp` is usually recovered from the stack. If the stack got invalidated due to unrestricted stack writes this would lose the value of `gp`. So we simply ignore load instructions that would overwrite `gp` with a `Top` value. This …
=> MIPS: prevent gp register value loss

src/cwe_checker_lib/src/intermediate_representation/bitvector.rs
The analysis may encounter division-by-zero in an analyzed binary, e.g. because of a division-by-zero bug in the analyzed binary or because of analysis inaccuracies like following an infeasible execution path. Until now the analysis panicked when encountering integer divisions by zero. Now we prevent the panic and return a proper error to allow analyses to continue in these cases.
Note that this PR does not implement a division-by-zero CWE-check.
=> Do not panic on encountered divisions by zero

src/caller/src/main.rs, src/cwe_checker_lib/src/analysis/pointer_inference/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/statistics.rs, src/cwe_checker_lib/src/utils/log.rs
Now debug log messages are not printed unless the `--verbose` command line flag is set. Furthermore, log messages generated by `--statistics` are now generally info log messages and if `--statistics` is set we also count the number of debug log messages per analysis and print the number as an info log messages.
=> Add --verbose cmdline flag

src/cwe_checker_lib/src/analysis/pointer_inference/mod.rs, src/cwe_checker_lib/src/checkers/cwe_134.rs, src/cwe_checker_lib/src/checkers/cwe_190.rs, src/cwe_checker_lib/src/checkers/cwe_243.rs, src/cwe_checker_lib/src/checkers/cwe_332.rs, src/cwe_checker_lib/src/checkers/cwe_367.rs, src/cwe_checker_lib/src/checkers/cwe_426.rs, src/cwe_checker_lib/src/checkers/cwe_467.rs, src/cwe_checker_lib/src/checkers/cwe_476.rs, src/cwe_checker_lib/src/checkers/cwe_560.rs, src/cwe_checker_lib/src/checkers/cwe_676.rs, src/cwe_checker_lib/src/checkers/cwe_78.rs, src/cwe_checker_lib/src/checkers/cwe_782.rs
Each check now sorts its generated CWE warnings by the corresponding address. Fixes #220.
=> Sort generated CWE warnings by address

.github/workflows/docker-publish-stable.yml, .github/workflows/docker-publish.yml
Automatically build and publish Docker images on the ghcr.io container registry. Images are generated for pushes to the master branch (with tag 'latest') and for published releases (with tag the release tag). The Readme.md will be updated in a separate PR if this PR works as intended.
=> Publish Docker images on ghcr.io

.github/workflows/docker-publish-stable.yml, .github/workflows/docker-publish.yml
The Github action for automatically deploying Docker images is extended to also push the Docker images to Dockerhub.  This way we are no longer dependent on the automatic build feature of Dockerhub and can keep Dockerhub as the default container registry for cwe_checker Docker images.
Note that we keep ghcr.io as a secondary container registry so that we can quickly switch to it if Dockerhub deployments should break again in the future.
=> Add automatic pushes to Dockerhub to the CI

src/cwe_checker_lib/src/abstract_domain/data.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/trait_impls.rs, src/cwe_checker_lib/src/analysis/pointer_inference/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/access_handling.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/tests.rs, test/src/lib.rs
This PR adds a heuristic to detect cases where a buffer overflow CWE warning is in reality a potential NULL dereference. These cases are now correctly classified as NULL dereference CWE warnings.
=> Correctly classify some buffer overflows as NULL dereferences

src/cwe_checker_lib/src/analysis/pointer_inference/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/tests.rs
Entry points are now generated with a list of generic parameter objects in the *Pointer Inference* analysis. In some cases this drastically increases the number of tracked memory operations, which at the moment outweighs the risk of introducing analysis errors through this change.
=> add generic parameter objects for entry points

src/caller/src/main.rs, src/cwe_checker_lib/src/analysis/backward_interprocedural_fixpoint/tests.rs, src/cwe_checker_lib/src/analysis/dead_variable_elimination/mod.rs, src/cwe_checker_lib/src/analysis/graph.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/mod.rs, src/cwe_checker_lib/src/checkers/cwe_367.rs, src/cwe_checker_lib/src/checkers/cwe_476/context.rs, src/cwe_checker_lib/src/checkers/cwe_676.rs, src/cwe_checker_lib/src/checkers/cwe_78.rs, src/cwe_checker_lib/src/checkers/cwe_78/context/tests.rs, src/cwe_checker_lib/src/intermediate_representation/program.rs, src/cwe_checker_lib/src/intermediate_representation/project.rs, src/cwe_checker_lib/src/pcode/term.rs, src/cwe_checker_lib/src/utils/symbol_utils.rs
Save the extern symbols in a BTreeMap instead of a list in the program struct to simplify lookup operations of extern symbols.
=> Minor project struct refactoring

src/cwe_checker_lib/src/abstract_domain/data.rs, src/cwe_checker_lib/src/abstract_domain/data/arithmetics.rs, src/cwe_checker_lib/src/abstract_domain/data/conditional_specialization.rs, src/cwe_checker_lib/src/abstract_domain/data/trait_impl.rs, src/cwe_checker_lib/src/abstract_domain/identifier.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object_list/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/tests.rs, src/cwe_checker_lib/src/checkers/cwe_476/state.rs
The way abstract locations are represented in abstract identifiers is refactored. This should make them a little bit more useful.
=> Refactor abstract identifiers

src/cwe_checker_lib/src/pcode/term.rs, src/cwe_checker_lib/src/pcode/term/tests.rs
Fixes a bug reported in issue #247: There were some corner cases where we did not check whether a P-Code instruction contains an implicit Store instruction, which caused the translation from P-Code to the internal intermediate representation to fail.
=> Always check for implicit Stores in P-Code instructions

src/cwe_checker_lib/src/intermediate_representation/expression.rs
Fixes the error reported in issue #262: In some cases where a sub-register was used in an implicit SUBPIECE instruction, the size of the result value was incorrectly computed.
=> Fix size computation of implicit subpiece instructions

Makefile, src/cwe_checker_lib/src/analysis/backward_interprocedural_fixpoint/tests.rs, src/cwe_checker_lib/src/analysis/dead_variable_elimination/mod.rs, src/cwe_checker_lib/src/analysis/forward_interprocedural_fixpoint.rs, src/cwe_checker_lib/src/analysis/function_signature/context.rs, src/cwe_checker_lib/src/analysis/graph.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/trait_impls.rs, src/cwe_checker_lib/src/analysis/string_abstraction/context/trait_impls.rs, src/cwe_checker_lib/src/analysis/string_abstraction/context/trait_impls/tests.rs, src/cwe_checker_lib/src/checkers/cwe_476/context.rs, src/cwe_checker_lib/src/intermediate_representation/project.rs, src/cwe_checker_lib/src/intermediate_representation/project/block_duplication_normalization.rs, src/cwe_checker_lib/src/intermediate_representation/sub.rs, src/cwe_checker_lib/src/pcode/term.rs, src/ghidra/p_code_extractor/internal/TermCreator.java, src/ghidra/p_code_extractor/term/Call.java, src/ghidra/p_code_extractor/term/Sub.java, test/src/lib.rs
Use Ghidra's inferred calling convention (pulling through from plugin) for internal functions, thus we fix PE issues around calling conventions. Also forced sequential test execution in the Makefile (concurrency causes non-deterministic errors)
=> Fixed issue #250 by using correct calling convention.

src/cwe_checker_lib/src/intermediate_representation/bitvector.rs
Fixes #268.
If a boolean value is something else than 0 or 1 then the handling of boolean negation is possibly wrong. This is fixed by just asserting that the boolean value is 0 or 1. This way the cwe_checker crashes if this actually occurs somewhere and we are hopefully alerted of it so that we can fix the root cause of the bug. I tested it with several different binaries without any observed crashes. So I am confident that such bugs either do only occur very rarely or do not currently exist in the code base.
=> Ensure correct handling of boolean negation

src/cwe_checker_lib/src/analysis/fixpoint.rs, src/cwe_checker_lib/src/analysis/interprocedural_fixpoint_generic.rs
Fixes #272.
The default value was not used internally by the fixpoint computation. As a solution, the default value is now explicitly assigned to all nodes on creation of a fixpoint computation. Consequently, the computation struct does not save the default value internally anymore.
=> Fix handling of default values for fixpoint computations

src/ghidra/p_code_extractor/internal/HelperFunctions.java, src/ghidra/p_code_extractor/internal/ParseCspecContent.java, src/ghidra/p_code_extractor/internal/TermCreator.java
Fix some issues that lead to panics when trying to analyze binaries using the AVR8 instruction set architecture. However, some issues remain and thus it is still not possible to analyze AVR8-binaries (see issue #284 for details).
=> fix some (but not all) AVR8 issues

.github/workflows/codestyle_checks.yml, Makefile, src/cwe_checker_lib/src/analysis/string_abstraction/context/mod.rs, src/cwe_checker_lib/src/intermediate_representation/blk.rs, src/cwe_checker_lib/src/intermediate_representation/project/block_duplication_normalization.rs
Fixes some broken intra-documentation links. Also adds a documentation build pass to the CI, so that it now automatically fails if broken documentation links (or other documentation warnings) are detected.
=> Fix intra-documentation links

src/cwe_checker_lib/src/intermediate_representation/bitvector.rs
The `apint` crate that we use to represent bitvectors does not yet support division of bitvectors of length longer than 8 bytes. We catch these cases and just do not execute such operations (and instead approximate them with an unknown result in the corresponding abstract domain). But we forgot to also catch the "compute remainder" versions of bitvector division, which lead to crashes when they occured. This PR fixes that.
Fixes issue #307.
=> fix crash on division of bitvectors longer than 8 bytes

src/caller/src/main.rs, src/cwe_checker_lib/src/analysis/pointer_inference/mod.rs, src/cwe_checker_lib/src/checkers.rs, src/cwe_checker_lib/src/checkers/cwe_119/context/mod.rs, src/cwe_checker_lib/src/checkers/cwe_119/context/tests.rs, src/cwe_checker_lib/src/checkers/cwe_119/mod.rs, src/cwe_checker_lib/src/checkers/cwe_416/context.rs, src/cwe_checker_lib/src/checkers/cwe_416/mod.rs, src/cwe_checker_lib/src/checkers/cwe_416/state.rs, src/cwe_checker_lib/src/lib.rs, test/src/lib.rs
Implement a new check for the CWEs CWE-415: Double Free and CWE-416: Use After Free. This check will replace the old check directly integrated into the Pointer Inference analysis. However, the old check is not yet removed from the code, as we plan to evaluate and improve the new check in comparison to the old one before removing the old check. 
Edit: There is also a known bug where this check ignores any knowledge about external functions that never return (which leads to false positive CWE warnings through considering infeasible paths during the analysis). This will be fixed in a separate PR.
=> Implement new CWE-416 check

test/src/lib.rs
We can now activate some acceptance tests for x86-gcc that were failing prior to PR #317.
=> activate more x86 acceptance tests

src/cwe_checker_lib/src/checkers/cwe_119/context/mod.rs, src/cwe_checker_lib/src/checkers/cwe_119/state.rs
Fix incorrect computation of object bounds if a parameter points to the caller stack in the CWE-119 check.
=> fix stack frame bounds computation

.github/workflows/docker-publish-stable.yml, .github/workflows/docker-publish.yml
Update the CI actions to use the newest versions of the corresponding Github Actions when building and publishing the Docker containers. Also disable the cross compilation Docker build for the ARM64 target. Apparently this leads to memory exhaustion problems in the CI, which in turn lead to the corresponding action getting killed before completion. We either have to wait until this gets fixed upstream by the Docker cross compilation build environment or we have to find a way to build the ARM versions of the Docker containers that does not rely on emulation.
=> Update docker action

src/cwe_checker_lib/src/analysis/function_signature/state/call_handling.rs
Correctly filter generic output IDs generated in the FnSig algorithm for those that are pointer-sized. This fixes a bug that lead to crashes for MIPS binaries.
=> Ensure that generic output IDs are pointer sized in FnSig analysis

src/ghidra/p_code_extractor/internal/JumpProcessing.java
Fix a bug that caused duplicated block terms to be created in the rare case that the target of an intra-instruction conditional jump to the fallthrough instruction was already the start of a regular block term. These duplicated blocks were empty and caused errors in the control flow graph.
=> Bugfix: prevent creation of duplicated block term

.github/workflows/acceptance-tests.yml, Cargo.lock, Dockerfile, README.md, src/caller/Cargo.toml, src/caller/src/main.rs, src/cwe_checker_lib/Cargo.toml, src/installer/Cargo.toml, src/installer/src/main.rs
Switch from the old `structopt` crate to `clap` v4.0. Also update some other dependencies and bump minimal required Rust version to 1.63.
This could change some special cases in command line parsing, although we made sure that the general command line parsing logic stays the same. If someone is affected by changed command line parsing behavior because of the switch, please open an issue.
=> switch to clap from structopt

src/cwe_checker_lib/src/abstract_domain/identifier.rs, src/cwe_checker_lib/src/analysis/callgraph.rs, src/cwe_checker_lib/src/analysis/function_signature/context.rs, src/cwe_checker_lib/src/analysis/function_signature/context/tests.rs, src/cwe_checker_lib/src/analysis/function_signature/global_var_propagation.rs, src/cwe_checker_lib/src/analysis/function_signature/mod.rs, src/cwe_checker_lib/src/analysis/function_signature/state.rs, src/cwe_checker_lib/src/analysis/function_signature/state/call_handling.rs, src/cwe_checker_lib/src/analysis/function_signature/state/tests.rs, src/cwe_checker_lib/src/analysis/mod.rs, src/cwe_checker_lib/src/intermediate_representation/expression.rs, src/cwe_checker_lib/src/intermediate_representation/jmp.rs
The function signature analysis now tracks accesses to global memory, i.e. it generates information on which global variables are accessed by each function. The implementation is geared towards usage with other bottom-up analyses. Note that the generated information about global variables is not yet used by any analysis. It is planned to use this information in the pointer inference analysis in the future.
=> add global memory tracking to FunctionSignature analysis

src/cwe_checker_lib/src/utils/arguments.rs, src/cwe_checker_lib/src/utils/arguments/tests.rs
Improve the regular expression used for parsing C-like format string parameters. Fixes a bug where parsing of the format string `%s,` resulted in a crash.
Note that the improved regular expression is still not 100% exact as it may assume some malformed format string parameters to be correct. Please open an issue if you encounter a format string used in a real-world binary that is not parsed correctly.
=> fix format string parsing bug

src/cwe_checker_lib/src/analysis/backward_interprocedural_fixpoint/mod.rs, src/cwe_checker_lib/src/analysis/fixpoint.rs, src/cwe_checker_lib/src/analysis/forward_interprocedural_fixpoint.rs, src/cwe_checker_lib/src/analysis/pointer_inference/mod.rs
Introduces a new worklist order for the forward interprocedural fixpoint computation. This order prefers nodes of callees and is verified by a test.
=> Worklist order edit

src/cwe_checker_lib/src/analysis/function_signature/context.rs, src/cwe_checker_lib/src/analysis/function_signature/global_var_propagation.rs, src/cwe_checker_lib/src/analysis/function_signature/mod.rs, src/cwe_checker_lib/src/analysis/function_signature/state.rs, src/cwe_checker_lib/src/analysis/function_signature/state/call_handling.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/id_manipulation.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/context/trait_impls.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object_list/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/object_list/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/access_handling.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/mod.rs, src/cwe_checker_lib/src/analysis/pointer_inference/state/tests.rs, src/cwe_checker_lib/src/analysis/pointer_inference/statistics.rs, src/cwe_checker_lib/src/analysis/string_abstraction/state/tests.rs, src/cwe_checker_lib/src/checkers/cwe_119/context/tests.rs, src/cwe_checker_lib/src/checkers/cwe_416/state.rs, src/cwe_checker_lib/src/checkers/cwe_467.rs, src/cwe_checker_lib/src/checkers/cwe_476/state.rs, src/cwe_checker_lib/src/checkers/cwe_560.rs, src/cwe_checker_lib/src/utils/arguments/tests.rs
Variables in mutable global memory are now also tracked by the Pointer Inference analysis.
Note that in the current implementation knowledge about global memory variables is only transmitted from callee to caller if the caller also accesses the same global variables in some way. Also, global variables are often used to transmit data between functions that are not in some caller-callee relationship, for which no data is shared between the functions in a bottom-up analysis anyway. So, the current implementation will mostly help with keeping track of global variables on an intraprocedural level, while interprocedural data sharing about global variables is possible, but wil not happen very often.
=> Implement global memory tracking for Pointer Inference

src/cwe_checker_lib/src/intermediate_representation/expression/tests.rs, src/cwe_checker_lib/src/intermediate_representation/expression/trivial_operation_substitution.rs
This time substitute a complicated expression generated on ARM by the equivalent `a < b` for signed integers.
=> substitute more trivial expressions

src/cwe_checker_lib/src/analysis/callgraph.rs, src/cwe_checker_lib/src/checkers/cwe_119/context/mod.rs, src/cwe_checker_lib/src/checkers/cwe_119/state.rs, src/cwe_checker_lib/src/intermediate_representation/program.rs
For a CWE-119 warning, emit a list of TIDs of all calls necessary to reach both the allocation site of the relevant memory object and the site of the buffer overflow warning from a common root function. The TID of the root function is also contained in the list as the first element. The list is emitted in the "other" field of the JSON output of the corresponding CWE warning.
This list is meant to help with both manual or automatic verification of a warning, as it should contain almost all relevant calls for the verification process. Of course, only looking at the calls in the list will not be enough in general, but at least most false positives can already be identified by only looking at the functions given by the calls in the list.
=> Generate call trace information for CWE-119 check

.github/workflows/acceptance-tests.yml, Dockerfile, README.md, src/cwe_checker_lib/src/abstract_domain/interval/simple_interval.rs, src/cwe_checker_lib/src/analysis/string_abstraction/state/mod.rs, src/cwe_checker_lib/src/checkers/cwe_476.rs, src/cwe_checker_lib/src/checkers/cwe_78.rs, src/cwe_checker_lib/src/pcode/term.rs, src/cwe_checker_lib/src/utils/log.rs, src/ghidra/p_code_extractor/internal/HelperFunctions.java, src/ghidra/p_code_extractor/internal/ParseCspecContent.java, src/installer/src/main.rs
Ghidra 10.2 fixed a typo in a function name in its API. This is now also fixed in the corresponding script of the cwe_checker. Unfortunately, this makes it a breaking change, i.e. now the cwe_checker requires Ghidra versions >= 10.2, while older cwe_checker versions do not work with Ghidra 10.2.
For users of the Docker images this should be a painless transition, while users of a local installation need to update their Ghidra installations manually and explicitly execute `make uninstall` before reinstalling the cwe_checker.
The PR also includes slight improvements to the installer, so that several Ghidra installation folders in the same parent folder are found when scanning for Ghidra versions.
=> switch to Ghidra 10.2

src/cwe_checker_lib/src/analysis/stack_alignment_substitution/mod.rs, src/cwe_checker_lib/src/analysis/stack_alignment_substitution/tests.rs
The stack_alignment_substitution-Analysis only considered the first block of every sub for replacing AND-Operations. If a sub has leading blocks without defs, this analysis does not alter the function at all.
Such empty blocks might be generated by `endbr`-like instructions, which sometimes are the first instructions of a function.
The analysis was edited and now skips leading, empty blocks of a function.
=> fixed bug of stack_alignment_substitution analysis

src/cwe_checker_lib/src/checkers/cwe_119/state.rs
The metadata generated for CWE-119 warnings was missing some calls in the list of callgraph TIDs in some cases.
=> CWE metadata fix

src/ghidra/p_code_extractor/internal/TermCreator.java
For some reason Ghidra generates register accesses for non-existing registers in some cases for Aarch64 binaries, which lead to crashes in the P-Code-Extractor component. These cases may be Ghidra errors (at least the generated P-Code looks nonsensical), but as a workaround they are now represented as virtual registers in the cwe_checker.
=> handle nameless registers in Ghidra

src/cwe_checker_lib/src/checkers/cwe_119/context/mod.rs, src/cwe_checker_lib/src/checkers/cwe_119/context/tests.rs, src/cwe_checker_lib/src/checkers/cwe_119/stubs.rs
The behavior of allocation functions like `malloc(size)` is usually implementation-specific if the size parameter is zero. However, these cases often resulted in false positive CWE-119 (buffer overflow) warnings. Now the CWE-119 check generates log messages for cases of zero-sized allocations, but does not assume that an actual heap object with size zero gets created. As a fallback, in cases where the minimum object size would be zero, the CWE-119 check now uses the maximum object size instead when looking for buffer overflows.
=> generate log messages for zero-sized allocations instead of CWE warnings

README.md, src/cwe_checker_lib/src/lib.rs
Since Dockerhub became less open-source-friendly (again!), we decided to migrate the official cwe_checker Docker images to the Github container registry.
=> Migrate the official Docker images to ghcr.io

Dockerfile
Update the Ghidra version contained in our Docker images to Ghidra 10.2.3. Also move the base image for the Docker image from Dockerhub to the Github container registry.
=> Update to Ghidra 10.2.3

Cargo.lock, Dockerfile, README.md, src/cwe_checker_lib/src/abstract_domain/identifier.rs, src/cwe_checker_lib/src/analysis/string_abstraction/context/symbol_calls/sprintf/tests.rs, src/cwe_checker_lib/src/checkers/cwe_416/context.rs, src/cwe_checker_lib/src/checkers/cwe_416/mod.rs, src/cwe_checker_lib/src/checkers/cwe_416/state.rs, src/cwe_checker_lib/src/intermediate_representation/macros/mod.rs
Now CWE-415- and CWE-416-warnings contain more precise context information in their JSON-representation, including a list of relevant callgraph IDs usable for downstream analyses.
Furthermore, we could reduce the number of duplicate CWEs by detecting cases where an object was freed and triggered an use-after-free warning in the same callee. Before this PR, the object could trigger additional use-after-free warnings in the caller, although these were essentially duplicates of the warning generated in the callee.
=> Generate context information for CWE-416 warnings

src/cwe_checker_lib/src/analysis/function_signature/global_var_propagation.rs, src/cwe_checker_lib/src/analysis/function_signature/mod.rs
The globals propagation algorithm (part of the function signature computation) can apparently not converge in some rare cases. Now we generate an error-log-message when that happens instead of panicking outright.
=> Prevent panic on non-converging globals propagation

src/cwe_checker_lib/src/analysis/expression_propagation/mod.rs, src/cwe_checker_lib/src/intermediate_representation/expression.rs
In rare cases the expression propagation fixpoint algorithm used huge amounts of RAM and computation time due to very large expressions that needed to be cloned repeatedly. We now enforce a complexity limit for expressions to be propagated in the expression propagation to prevent this behavior.
Fixes #410.
=> prevent huge expressions during expression propagation

src/config.json, src/cwe_checker_lib/src/checkers/cwe_119/context/mod.rs, src/cwe_checker_lib/src/checkers/cwe_416/context.rs, src/cwe_checker_lib/src/checkers/cwe_416/mod.rs
We now support more allocation and deallocation symbols, like `realloc` and the C++ `new` and `delete` operators, in the `Memory` analysis and the CWE-119 and CWE-416-checks.
Also, the deallocation symbols for the CWE-416-check are now configurable in the `config.json`. This way you can, for example, disable the support for `realloc` if it leads to a large amount of false positive warnings on your binaries.
=> support more allocation and deallocation functions

CHANGES.md, CONTRIBUTORS.md, Cargo.lock, README.md, src/caller/Cargo.toml, src/cwe_checker_lib/Cargo.toml, src/cwe_checker_lib/src/lib.rs, src/installer/Cargo.toml
Highlights of v0.7 compared to v0.6: One new check (CWE789: memory allocation with excessive size value) and many improvements under the hood, including generation of better meta-information in the CWE-warnings of the CWE-119 and CWE-416 checks.
=> prepare v0.7 stable release

src/config.json, src/cwe_checker_lib/src/checkers/cwe_416/mod.rs, src/cwe_checker_lib/src/checkers/cwe_416/state.rs
The CWE-416 check (for Use-After-Free bugs) now has a configuration option regulating the amount of call-graph path information contained in the JSON output of its warnings. If it is activated, then full paths to an actual "free" operation are included in the JSON output. This is useful when verifying such a CWE warning (manually or automatically), although it also increases the amount of code one has to look at (which can be a drawback for automatic verification algorithms).
Currently, the new configuration option is activated by default. It can be deactivated via the `config.json` file.
=> optionally generate full path to "free" site in CWE-416 warnings

src/cwe_checker_lib/src/analysis/expression_propagation/mod.rs, src/cwe_checker_lib/src/analysis/expression_propagation/tests.rs, src/ghidra/p_code_extractor/internal/ParseCspecContent.java
The expression compexity limit during the expression propagation algorithm was not enforced during the final expression substitution step. This could lead to excessive RAM usage in rare cases.
This PR also fixes a typo in the previous PR #427.
=> always enforce expression complexity limit

src/cwe_checker_lib/src/abstract_domain/identifier/mod.rs, src/cwe_checker_lib/src/analysis/fixpoint.rs, src/cwe_checker_lib/src/analysis/function_signature/context/tests.rs, src/cwe_checker_lib/src/analysis/function_signature/mod.rs, src/cwe_checker_lib/src/analysis/function_signature/state/memory_handling.rs, src/cwe_checker_lib/src/analysis/function_signature/state/mod.rs, src/cwe_checker_lib/src/analysis/function_signature/state/tests.rs, src/cwe_checker_lib/src/checkers/cwe_416/mod.rs, src/cwe_checker_lib/src/checkers/cwe_416/state.rs
Since tracking of nested parameter objects greatly increased the amount of tracked memory objects, it also greatly increased the amount of false positives found by the CWE-416 Use After Free check. This PR implements several heuristic mitigations designed to reduce the number of false positives found by the check:
- If an object gets freed in the same call as it was created, the `dangling` status of its pointer is not propagated to callers. A common pattern is to free freshly created objects on errors and return a null pointer instead. But the analysis cannot yet track the invariant that the pointer is only returned when it is not freed, so we have to handle this pattern heuristically.
- If an object gets freed and subsequently generates a Use After Free warning in the same call then the …
=> Reduce false positives in CWE-416 check

Dockerfile, README.md, src/caller/Cargo.toml, src/cwe_checker_lib/Cargo.toml, src/installer/Cargo.toml
Also add minimal supported Rust version to `Cargo.toml` files.
Add the minimal supported Rust version to `Cargo.toml` files to fail the
build as early as possible if the used Rust version is too old.
=> Bump minimal supported Rust version to 1.73

src/cwe_checker_lib/src/abstract_domain/bitvector.rs, src/cwe_checker_lib/src/abstract_domain/interval.rs, src/cwe_checker_lib/src/abstract_domain/interval/tests.rs, src/cwe_checker_lib/src/abstract_domain/mod.rs, src/cwe_checker_lib/src/intermediate_representation/bitvector.rs, src/cwe_checker_lib/src/intermediate_representation/expression.rs, src/cwe_checker_lib/src/pcode/expressions.rs, src/cwe_checker_lib/src/pcode/term.rs
Implement support for the LZCOUNT P-Code operation introduced in Ghidra 10.3.
This was originally meant to be implemented alongside a major refactoring of the P-Code parsing code. But since that refactoring will need longer than expected, we have to support it now so that we can keep up with newer Ghidra versions.
=> Implement LZCOUNT P-Code operation

Dockerfile
Update the Ghidra version used in the Docker image to the newest Ghidra release.
=> update Ghidra version in Docker image

src/cwe_checker_lib/src/intermediate_representation/blk.rs, src/cwe_checker_lib/src/intermediate_representation/program.rs, src/cwe_checker_lib/src/intermediate_representation/sub.rs
Implement the `Display` trait for the intermediate language representation of the analyzed program.
This outputs a human-friendly representation that is more compact than what is returned by `Debug` and is therefore easier to consume.
There are no direct users of this implementation, its main purpose is to facilitate easier debugging during development.
For example, the following C program becomes:
```C
int say_hello(char *msg)
{
if (msg)
printf("Hello, World: %s\n", msg);
return 42;
}
```
```
[...]
SUB [sub_00101110] n:say_hello e:1
BLK [blk_00101110]
DEF [instr_00101110_0] CF:1 = 0x0:1
DEF [instr_00101110_1] OF:1 = 0x0:1
DEF [instr_00101110_2] $U56080:8(temp) = (RDI:8 & RDI:8)
DEF [instr_00101110_3] SF:1 = ($U56080:8(temp) < 0x0:8)
DEF [instr_00101110_4] ZF:1 = ($U56080:8(temp) == …
```
=> ir: impl `Display` for `Program`
